"""
Supervised Fine-Tuning Script for Abyme using Unsloth

This script fine-tunes DeepSeek-R1-Distill-Llama-8B on recursive reasoning traces
generated by generate_training_dataset.py.

Optimized for 4080 (12GB VRAM) or Lambda Cloud H100.
"""

import os
import sys
import torch
from datasets import load_dataset
from transformers import TrainingArguments
from trl import SFTTrainer
from unsloth import FastLanguageModel

# Add parent directory to path to import abyme modules
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
from abyme.tokenization import inject_special_tokens

# Configuration
MODEL_NAME = "unsloth/DeepSeek-R1-Distill-Llama-8B-unsloth-bnb-4bit"
TRAINING_DATA = "abyme-rllm/sft/training_data.jsonl"
OUTPUT_DIR = "checkpoints/sft_run"
MAX_SEQ_LENGTH = 4096

# LoRA configuration
LORA_R = 16
LORA_ALPHA = 16
LORA_DROPOUT = 0.0
TARGET_MODULES = [
    "q_proj",
    "k_proj",
    "v_proj",
    "o_proj",
    "gate_proj",
    "up_proj",
    "down_proj"
]

# Training configuration
BATCH_SIZE = 2
GRADIENT_ACCUMULATION_STEPS = 4
LEARNING_RATE = 2e-4
NUM_EPOCHS = 3
WARMUP_STEPS = 10
LOGGING_STEPS = 10
SAVE_STEPS = 100


def setup_model():
    """
    Load the Unsloth model and tokenizer, then inject special tokens.

    Returns:
        tuple: (model, tokenizer)
    """
    print("=" * 80)
    print("Setting up model and tokenizer...")
    print("=" * 80)

    # Load model and tokenizer using Unsloth
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=MODEL_NAME,
        max_seq_length=MAX_SEQ_LENGTH,
        dtype=None,  # Auto-detect
        load_in_4bit=True,
    )

    print(f"Model loaded: {MODEL_NAME}")
    print(f"Original vocab size: {len(tokenizer)}")

    # Inject Abyme special tokens (<elaborate>, </elaborate>, <response>, </response>, </run>)
    # This MUST be done before applying LoRA
    print("\nInjecting special tokens for recursive reasoning...")
    model, tokenizer = inject_special_tokens(model, tokenizer)

    print(f"New vocab size: {len(tokenizer)}")

    # Apply LoRA for parameter-efficient fine-tuning
    print("\nApplying LoRA configuration...")
    model = FastLanguageModel.get_peft_model(
        model,
        r=LORA_R,
        target_modules=TARGET_MODULES,
        lora_alpha=LORA_ALPHA,
        lora_dropout=LORA_DROPOUT,
        bias="none",
        use_gradient_checkpointing="unsloth",
        random_state=42,
    )

    print(f"LoRA applied with r={LORA_R}, alpha={LORA_ALPHA}")
    print("=" * 80)

    return model, tokenizer


def load_training_data(tokenizer):
    """
    Load and prepare the training dataset.

    Args:
        tokenizer: The tokenizer to use for processing

    Returns:
        Dataset object
    """
    print("\nLoading training data...")
    print(f"Data file: {TRAINING_DATA}")

    if not os.path.exists(TRAINING_DATA):
        raise FileNotFoundError(
            f"Training data not found at {TRAINING_DATA}. "
            "Please run generate_training_dataset.py first."
        )

    # Load JSONL dataset
    dataset = load_dataset('json', data_files=TRAINING_DATA, split='train')

    print(f"Loaded {len(dataset)} training examples")

    # Print a sample
    if len(dataset) > 0:
        print("\nSample training example:")
        print("-" * 80)
        print(f"Prompt: {dataset[0]['prompt'][:100]}...")
        print(f"Completion length: {len(dataset[0]['completion'])} chars")
        print(f"Category: {dataset[0].get('category', 'N/A')}")
        print("-" * 80)

    return dataset


def format_prompt(example):
    """
    Format the training example into a single text field.

    The completion already contains the full trace including <think> tags
    and recursive structure.

    Args:
        example: A single training example

    Returns:
        Formatted example with 'text' field
    """
    # Format: User prompt + Assistant completion
    text = f"### User:\n{example['prompt']}\n\n### Assistant:\n{example['completion']}"
    return {"text": text}


def train():
    """
    Main training function.
    """
    print("\n" + "=" * 80)
    print("ABYME SUPERVISED FINE-TUNING")
    print("=" * 80)

    # Setup model and tokenizer
    model, tokenizer = setup_model()

    # Load dataset
    dataset = load_training_data(tokenizer)

    # Format dataset
    print("\nFormatting dataset...")
    dataset = dataset.map(format_prompt, remove_columns=dataset.column_names)

    # Create output directory
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # Configure training arguments
    training_args = TrainingArguments(
        output_dir=OUTPUT_DIR,
        per_device_train_batch_size=BATCH_SIZE,
        gradient_accumulation_steps=GRADIENT_ACCUMULATION_STEPS,
        warmup_steps=WARMUP_STEPS,
        num_train_epochs=NUM_EPOCHS,
        learning_rate=LEARNING_RATE,
        fp16=not torch.cuda.is_bf16_supported(),
        bf16=torch.cuda.is_bf16_supported(),
        logging_steps=LOGGING_STEPS,
        save_steps=SAVE_STEPS,
        save_total_limit=3,
        optim="adamw_8bit",
        weight_decay=0.01,
        lr_scheduler_type="cosine",
        seed=42,
        report_to="none",  # Change to "wandb" if you want W&B logging
    )

    print("\nTraining Configuration:")
    print(f"  Batch size: {BATCH_SIZE}")
    print(f"  Gradient accumulation: {GRADIENT_ACCUMULATION_STEPS}")
    print(f"  Effective batch size: {BATCH_SIZE * GRADIENT_ACCUMULATION_STEPS}")
    print(f"  Learning rate: {LEARNING_RATE}")
    print(f"  Epochs: {NUM_EPOCHS}")
    print(f"  Max sequence length: {MAX_SEQ_LENGTH}")
    print(f"  Output directory: {OUTPUT_DIR}")
    print("=" * 80)

    # Create trainer
    trainer = SFTTrainer(
        model=model,
        tokenizer=tokenizer,
        train_dataset=dataset,
        dataset_text_field="text",
        max_seq_length=MAX_SEQ_LENGTH,
        args=training_args,
        packing=False,  # Don't pack sequences for now
    )

    # Disable cache for training
    model.config.use_cache = False

    print("\nStarting training...")
    print("=" * 80)

    # Train!
    trainer.train()

    print("\n" + "=" * 80)
    print("Training complete!")
    print("=" * 80)

    # Save the final model
    print("\nSaving model and tokenizer...")

    # Save LoRA adapters
    model.save_pretrained(OUTPUT_DIR + "/final_lora")
    tokenizer.save_pretrained(OUTPUT_DIR + "/final_lora")

    print(f"LoRA adapters saved to: {OUTPUT_DIR}/final_lora")

    # Optionally merge and save full model (requires more disk space)
    save_merged = input("\nMerge LoRA adapters into base model? (y/n): ").lower() == 'y'

    if save_merged:
        print("Merging LoRA adapters into base model...")
        merged_model = FastLanguageModel.merge_and_unload(model)
        merged_model.save_pretrained(OUTPUT_DIR + "/merged_model")
        tokenizer.save_pretrained(OUTPUT_DIR + "/merged_model")
        print(f"Merged model saved to: {OUTPUT_DIR}/merged_model")

    print("\n" + "=" * 80)
    print("All done! 🎉")
    print("=" * 80)

    # Print next steps
    print("\nNext steps:")
    print("1. Test the model on unseen problems")
    print("2. Run local evaluation (Day 9 in PLAN.md)")
    print("3. Proceed to GRPO training (Phase 4)")
    print("\nTo load the trained model:")
    print(f"  model, tokenizer = FastLanguageModel.from_pretrained('{OUTPUT_DIR}/final_lora')")


if __name__ == "__main__":
    train()
