"""
Tree trace data structure for tracking recursive model generation.

This module provides the TreeTraceNode class, which records the complete
execution trace of a RecursiveModel's generation process as a tree structure.
Each node represents a single generation step, including prompt, context,
output, and relationships to subproblems and continuation nodes.
"""

from typing import List
from .utils import format_output


class TreeTraceNode:
    """
    Represents a single node in the recursive generation tree.

    A TreeTraceNode captures all information about a single generation step:
    - Input: prompt and context
    - Output: generated text and latency
    - Structure: depth level, subproblems, and continuation node
    - State: whether generation has completed

    **Tree Structure:**
    - `subproblems`: List of child nodes representing elaborations at depth+1
    - `next`: Continuation node at the same depth after subproblems are resolved
    - The tree follows the elaboration-continuation pattern of RecursiveModel

    **Example Tree:**
    ```
    root (depth=0, prompt="Solve X+Y")
    ├─ subproblem1 (depth=1, prompt="X")
    ├─ subproblem2 (depth=1, prompt="Y")
    └─ next (depth=0, prompt="Solve X+Y", context="...with X and Y solved...")
       └─ final output
    ```

    **Attributes:**
    - prompt (str): The problem or instruction to solve
    - context (str): Previously generated text providing context
    - depth (int): Recursion depth (0 = root, increases for subproblems)
    - is_generated (bool): Whether base model generation has completed
    - output (str): Raw output from base model (before format_output)
    - latency (float): Time taken for base model generation (seconds)
    - next (TreeTraceNode | None): Continuation node after subproblems resolved
    - subproblems (List[TreeTraceNode]): Child nodes for elaborations
    - final_output (str): Cached final output (lazily computed)
    """

    def __init__(self, prompt: str, context: str, depth: int):
        """
        Initialize a new TreeTraceNode.

        Args:
            prompt: The problem or instruction to solve at this node
            context: Previously generated text to provide as context
            depth: Current recursion depth (0 = root, increases for subproblems)
        """
        self.prompt = prompt
        self.context = context
        self.depth = depth
        self.is_generated = False  # True after record_generation is called
        self.output = ""  # Raw output from base model
        self.latency = 0.0  # Generation time in seconds
        self.next = None  # Continuation node (same depth, after subproblems)
        self.subproblems = []  # List of child TreeTraceNode instances (depth+1)
        self.final_output = ""  # Cached final output (computed by get_final_output)

    def record_generation(self, output: str, latency: float):
        """
        Record the output and latency from a base model generation.

        This method should be called once per node after the base model
        generates output for this node's prompt and context.

        Args:
            output: The raw output generated by the base model
            latency: Time taken for generation in seconds
        """
        self.is_generated = True
        self.latency = latency
        self.output = output

    def add_subproblem(self, subproblem_node):
        """
        Add a child node representing a subproblem (elaboration).

        Subproblem nodes are at depth+1 and represent elaborations
        that were extracted from this node's output.

        Args:
            subproblem_node: TreeTraceNode instance for the subproblem

        Raises:
            ValueError: If subproblem_node is not a TreeTraceNode instance
        """
        if not isinstance(subproblem_node, TreeTraceNode):
            raise ValueError("subproblem_node must be an instance of TreeTraceNode")
        self.subproblems.append(subproblem_node)

    def add_next(self, next_node):
        """
        Set the continuation node after subproblems are resolved.

        The next node continues generation at the same depth with updated
        context that includes resolved subproblem responses.

        Args:
            next_node: TreeTraceNode instance for the continuation

        Raises:
            ValueError: If next_node is not a TreeTraceNode instance
        """
        if not isinstance(next_node, TreeTraceNode):
            raise ValueError("next_node must be an instance of TreeTraceNode")
        self.next = next_node

    def get_final_output(self) -> str:
        """
        Get the final output by traversing the tree to its end.

        This method follows the `next` chain to the leaf node and returns
        its formatted output. The result is cached in `final_output`.

        **Traversal Logic:**
        1. If final_output is already cached, return it
        2. If this node hasn't been generated, raise an error
        3. If this is a leaf node (no next), format and return this node's output
        4. If there's a next node, recursively get its final output

        Returns:
            The final formatted output string

        Raises:
            Exception: If called on a node that hasn't been generated yet

        Example:
            >>> root = TreeTraceNode("Solve X", "", 0)
            >>> # ... generate and build tree ...
            >>> final = root.get_final_output()  # Returns formatted final answer
        """
        # Return cached result if available
        if self.final_output:
            return self.final_output

        # Ensure generation has completed
        if not self.is_generated:
            raise Exception("Output not generated yet")

        # Leaf node: format and cache this node's output
        if not self.next:
            self.final_output = format_output(self.output)
            return self.final_output

        # Non-leaf node: recursively get next node's final output
        self.final_output = self.next.get_final_output()
        return self.final_output


def flatten_trace(tree: TreeTraceNode) -> List[TreeTraceNode]:
    """
    Flatten the tree trace into a list in DFS manner where subproblems are explored first.

    This function traverses the tree in depth-first order, exploring all subproblems
    before adding the current node, then continuing with the next node.

    **Traversal Order:**
    1. Recursively flatten all subproblems (depth-first)
    2. Add the current node
    3. Recursively flatten the next node if it exists

    Args:
        tree: The root TreeTraceNode to flatten

    Returns:
        A list of TreeTraceNode instances in DFS order

    Example:
        >>> root = TreeTraceNode("Solve X+Y", "", 0)
        >>> # ... build tree ...
        >>> nodes = flatten_trace(root)
        >>> # Returns: [subproblem1_nodes..., subproblem2_nodes..., root, next_nodes...]
    """
    result: List[TreeTraceNode] = []

    # First, recursively flatten all subproblems (DFS)
    for subproblem in tree.subproblems:
        result.extend(flatten_trace(subproblem))

    # Add the current node
    result.append(tree)

    # Finally, recursively flatten the next node if it exists
    if tree.next is not None:
        result.extend(flatten_trace(tree.next))

    return result

def parallel_latency(tree: TreeTraceNode) -> float:
    """
    Calculate the total latency of the tree trace assuming parallel execution of subproblems.

    This function computes the total time taken for the entire generation process
    by considering that all subproblems at the same depth are executed in parallel.
    The latency is calculated as follows:
    1. For leaf nodes (no subproblems), return their latency.
    2. For non-leaf nodes, return the maximum latency among its subproblems plus its own latency.
    3. If a node has a next node, add its latency to the total.

    Args:
        tree: The root TreeTraceNode to calculate latency for

    Returns:
        The total latency assuming parallel execution of subproblems
    """
    if not tree.subproblems:
        return tree.latency

    subproblem_latencies = [parallel_latency(sub) for sub in tree.subproblems]
    max_subproblem_latency = max(subproblem_latencies)
    total_latency = tree.latency + max_subproblem_latency

    if tree.next is not None:
        total_latency += parallel_latency(tree.next)

    return total_latency

def total_calls(tree: TreeTraceNode) -> int:
    """
    Count the total number of generation calls in the tree trace.

    This function counts the total number of nodes in the tree, which corresponds
    to the total number of generation calls made during the recursive process.

    Args:
        tree: The root TreeTraceNode to count calls for

    Returns:
        The total number of generation calls (nodes) in the tree
    """
    count = 1  # Count the current node

    # Count all subproblems
    for subproblem in tree.subproblems:
        count += total_calls(subproblem)

    # Count the next node if it exists
    if tree.next is not None:
        count += total_calls(tree.next)

    return count

def max_depth(tree: TreeTraceNode) -> int:
    """
    Calculate the maximum depth of the tree trace.

    This function computes the maximum depth of the tree, which corresponds
    to the deepest level of recursion reached during the generation process.

    Args:
        tree: The root TreeTraceNode to calculate depth for

    Returns:
        The maximum depth of the tree
    """
    if not tree.subproblems:
        return tree.depth

    subproblem_depths = [max_depth(sub) for sub in tree.subproblems]
    return max(subproblem_depths)

def max_subproblem(tree: TreeTraceNode) -> int:
    """
    Calculate the maximum number of subproblems at any level in the tree trace.

    This function computes the maximum number of subproblems (children) that any node in the tree has,
    which corresponds to the maximum branching factor of the recursive generation process.
    
    Args:
        tree: The root TreeTraceNode to calculate max subproblems for
        
    Returns:
        The maximum number of subproblems at any level in the tree
    """
    max_subs = len(tree.subproblems)

    for subproblem in tree.subproblems:
        max_subs = max(max_subs, max_subproblem(subproblem))

    if tree.next is not None:
        max_subs = max(max_subs, max_subproblem(tree.next))

    return max_subs