"""
Tree trace data structure for tracking recursive model generation.

This module provides the TreeTraceNode class, which records the complete
execution trace of a RecursiveModel's generation process as a tree structure.
Each node represents a single generation step, including prompt, fragment,
output, and relationships to subproblems and continuation nodes.
"""

from typing import List, TypeVar, Callable, Optional, Literal
from .utils import format_output, AND, OR



class TreeTraceNode:
    """
    Represents a single node in the recursive generation tree.

    A TreeTraceNode captures all information about a single generation step:
    - Input: prompt and fragment
    - Output: generated text and latency
    - Structure: depth level, subproblems, and continuation node
    - State: whether generation has completed

    **Tree Structure:**
    - `subproblems`: List of child nodes representing elaborations at depth+1
    - `next`: Continuation node at the same depth after subproblems are resolved
    - The tree follows the elaboration-continuation pattern of RecursiveModel

    **Example Tree:**
    ```
    root (depth=0, prompt="Solve X+Y")
    ├─ subproblem1 (depth=1, prompt="X")
    ├─ subproblem2 (depth=1, prompt="Y")
    └─ next (depth=0, prompt="Solve X+Y", fragment="...with X and Y solved...")
       └─ final output
    ```

    **Attributes:**
    - prompt (str): The problem or instruction to solve
    - fragment (str): Previously generated text providing fragment
    - depth (int): Recursion depth (0 = root, increases for subproblems)
    - index (int): the position in the chain of next nodes at the same depth, starting from 0
    - status (NodeStatus): Current node status - "WAIT_SUB" (waiting for subproblems to complete), "GENERATING" (output being generating),
                           "COMPLETED" (all children returned), "FAILED" (generation failed), "WAIT_GEN" (waiting for generation)
    - node_type (NodeType): Type of node - "AND" (all children must succeed), "OR" (any child can succeed),
                            "LEAF" (output not yet generated or no branching or has no children)
    - output (str): Raw output from base model (before format_output)
    - latency (float): Time taken for base model generation (seconds)
    - next (TreeTraceNode | None): Continuation node after subproblems resolved
    - subproblems (List[TreeTraceNode]): Child nodes for elaborations
    - final_output (str): Cached final output (lazily computed)
    - difficulty (int): minimum number of calls needed to solve this problem
    """

    def __init__(self, prompt: str, fragment: str, depth: int, index:int):
        """
        Initialize a new TreeTraceNode.

        Args:
            prompt: The problem or instruction to solve at this node
            fragment: Previously generated text to provide as fragment
            depth: Current recursion depth (0 = root, increases for subproblems)
            index: The position in the chain of next nodes at the same depth, starting from 0
        """
        self.prompt:str = prompt
        self.fragment:str = fragment
        self.depth:int = depth
        self.index:int = index
        self.parent:Optional["TreeTraceNode"] = None # the parent node for subproblems, not used for next nodes, thus all depth 0 nodes have parent = None
        self.status: NodeStatus = "WAIT_GEN"  # Node starts in waiting for generation state
        self.node_type: NodeType = "LEAF"  # Type determined after generation
        self.output:str = ""  # Raw output from base model
        self.latency:float = 0.0  # Generation time in seconds
        self.next: Optional["TreeTraceNode"] = None  # Continuation node (same depth, after subproblems)
        self.subproblems: List["TreeTraceNode"] = []  # List of child TreeTraceNode instances (depth+1)
        self.final_output:str = ""  # Cached final output (computed by get_final_output)
        self.last_node: "TreeTraceNode" = self  # Track the last node in the next chain for easy appending of new nodes
        self.difficulty:int = 1 

    def record_generation(self, output: str, latency: float):
        """
        Record the output and latency from a base model generation.

        This method should be called once per node after the base model
        generates output for this node's prompt and fragment.
        Sets status to WAIT_SUB since children may need to be generated.

        Args:
            output: The raw output generated by the base model
            latency: Time taken for generation in seconds
        """
        self.status = "WAIT_SUB"  # Waiting for children to be generated (if any)
        self.latency = latency
        self.output = output

    def add_subproblems(self, subproblems: List[str]):
        """
        Add a child node representing a subproblem (elaboration).

        Subproblem nodes are at depth+1 and represent elaborations
        that were extracted from this node's output.

        Args:
            subproblem_node: TreeTraceNode instance for the subproblem

        Raises:
            ValueError: If subproblem_node is not a TreeTraceNode instance
        """
        for sub in subproblems:
            new_node = TreeTraceNode(sub, "", self.depth + 1, index=0)
            new_node.parent = self
            self.subproblems.append(new_node)
        self.difficulty = len(self.subproblems)

    def get_final_output(self) -> str:
        """
        Get the final output by traversing the tree to its end.

        This method follows the `next` chain to the leaf node and returns
        its formatted output. The result is cached in `final_output`.

        **Traversal Logic:**
        1. If final_output is already cached, return it
        2. If this node hasn't been generated, raise an error
        3. If this is a leaf node (no next), format and return this node's output
        4. If there's a next node, recursively get its final output

        Returns:
            The final formatted output string

        Raises:
            Exception: If called on a node that hasn't been generated yet

        Example:
            >>> root = TreeTraceNode("Solve X", "", 0)
            >>> # ... generate and build tree ...
            >>> final = root.get_final_output()  # Returns formatted final answer
        """
        # Return cached result if available
        if self.final_output:
            return self.final_output

        # Ensure generation has completed
        if self.status == "GENERATING":
            raise Exception("Output not generated yet")

        # Leaf node: format and cache this node's output
        if not self.next:
            self.final_output = format_output(self.output)
            return self.final_output

        # Non-leaf node: recursively get next node's final output
        self.final_output = self.next.get_final_output()
        return self.final_output
    
    def get_last(self) -> 'TreeTraceNode':
        """
        Get the last node in the next chain.

        This method follows the `next` chain to the end and returns
        the last node. This can be useful for appending new nodes to the end of the trace.

        Returns:
            The last TreeTraceNode in the next chain
        """
        if self.next is not None:
            self.last_node = self.next.get_last()
        return self.last_node
    
    def update_difficulty(self):
        """
        Update the difficulty of this node based on its subproblems.
        
        Args:
            subproblem_difficulties: List of difficulties from subproblems
        """
        # this is only applicable to the final node in the chain
        if self.next:
            self.get_last().update_difficulty()
            return
        if self.status == "COMPLETED":
            self.difficulty = 0
            return
        if self.status == "FAILED":
            self.difficulty = 9999999 #INF
            return
        if self.node_type == "LEAF":
            self.difficulty = 1
            return
        
        difficulties = []
        for sub in self.subproblems:
            sub_last = sub.get_last()
            sub_last.update_difficulty()
            difficulties.append(sub_last.difficulty)
        
        if self.node_type == "AND":
            self.difficulty = sum(difficulties) + 1
        elif self.node_type == "OR":
            self.difficulty = min(difficulties)
        return

T = TypeVar('T')

def fold(tree: TreeTraceNode, f: Callable[[TreeTraceNode, List[T], Optional[T]], T]) -> T:
    """
    Generic tree fold/reduce operation for TreeTraceNode.

    This is a higher-order function that traverses the tree structure and applies
    a combining function to compute a result. It provides a single abstraction
    for all tree traversal operations.

    **Traversal Pattern:**
    1. Recursively fold all subproblems
    2. Recursively fold the next node (if exists)
    3. Apply the combining function f to current node and recursive results

    Args:
        tree: The TreeTraceNode to fold
        f: A function that takes (node, subproblem_results, next_result) and
           returns a combined result. The function should handle:
           - node: Current TreeTraceNode
           - subproblem_results: List of results from folding each subproblem
           - next_result: Result from folding the next node (None if no next)

    Returns:
        The result of applying f across the entire tree structure

    Example:
        >>> # Count total nodes
        >>> count = fold(tree, lambda node, subs, next: 1 + sum(subs) + (next or 0))
        >>>
        >>> # Get maximum depth
        >>> max_d = fold(tree, lambda node, subs, next: max([0] + subs + ([next] if next else [])))
    """
    # Recursively fold all subproblems
    subproblem_results: List[T] = [fold(sub, f) for sub in tree.subproblems]

    # Recursively fold the next node if it exists
    next_result: Optional[T] = fold(tree.next, f) if tree.next is not None else None

    # Apply the combining function
    return f(tree, subproblem_results, next_result)

def find_next_to_generate(tree: TreeTraceNode) -> Optional[TreeTraceNode]:
    """
    Find the next node in the tree that is waiting for generation.

    This function performs a greedy depth-first search to find the first node
    with status "WAIT_GEN", which indicates it is waiting for generation using difficulty.

    Args:
        tree: The root TreeTraceNode to search
    """
    
    if tree.next:
        return find_next_to_generate(tree.get_last())
    
    # Base Case: If this node is waiting for generation, return it
    if tree.status == "WAIT_GEN":
        return tree
    elif tree.status == "FAILED":
        return None
    elif tree.status == "COMPLETED":
        return None
    elif tree.status == "GENERATING":
        return None
    
    else: # this node is waiting for subproblems to complete
        # generate the subproblem with minimal difficulty that is in any WAITING states
        for sub in sorted(tree.subproblems, key=lambda x: x.difficulty):
            if sub.status in ["WAIT_GEN", "WAIT_SUB"]:
                return find_next_to_generate(sub)
        return None


def flatten_trace(tree: TreeTraceNode) -> List[TreeTraceNode]:
    """
    Flatten the tree trace into a list in DFS manner where subproblems are explored first.

    This function traverses the tree in depth-first order, exploring all subproblems
    before adding the current node, then continuing with the next node.

    **Traversal Order:**
    1. Recursively flatten all subproblems (depth-first)
    2. Add the current node
    3. Recursively flatten the next node if it exists

    Args:
        tree: The root TreeTraceNode to flatten

    Returns:
        A list of TreeTraceNode instances in DFS order

    Example:
        >>> root = TreeTraceNode("Solve X+Y", "", 0)
        >>> # ... build tree ...
        >>> nodes = flatten_trace(root)
        >>> # Returns: [subproblem1_nodes..., subproblem2_nodes..., root, next_nodes...]
    """
    result: List[TreeTraceNode] = []

    # First, recursively flatten all subproblems (DFS)
    for subproblem in tree.subproblems:
        result.extend(flatten_trace(subproblem))

    # Add the current node
    result.append(tree)

    # Finally, recursively flatten the next node if it exists
    if tree.next is not None:
        result.extend(flatten_trace(tree.next))

    return result

def parallel_latency(tree: TreeTraceNode) -> float:
    """
    Calculate the total latency of the tree trace assuming parallel execution of subproblems.

    This function computes the total time taken for the entire generation process
    by considering that all subproblems at the same depth are executed in parallel.
    The latency is calculated as follows:
    1. For leaf nodes (no subproblems), return their latency.
    2. For non-leaf nodes, return the maximum latency among its subproblems plus its own latency.
    3. If a node has a next node, add its latency to the total.

    Args:
        tree: The root TreeTraceNode to calculate latency for

    Returns:
        The total latency assuming parallel execution of subproblems
    """
    subproblem_latencies = [parallel_latency(sub) for sub in tree.subproblems]
    if tree.node_type == "AND":
        max_subproblem_latency = max(subproblem_latencies, default=0)
    elif tree.node_type == "OR":
        max_subproblem_latency = min(subproblem_latencies, default=0)
    else:  # LEAF
        max_subproblem_latency = tree.latency
    total_latency = tree.latency + max_subproblem_latency

    if tree.next is not None:
        total_latency += parallel_latency(tree.next)

    return total_latency

def sequencial_latency(tree: TreeTraceNode) -> float:
    """
    Calculate the total latency of the tree trace assuming sequential execution of all nodes.

    This function computes the total time taken for the entire generation process
    by summing the latencies of all nodes in a depth-first manner, including subproblems and next nodes.

    Args:
        tree: The root TreeTraceNode to calculate latency for

    Returns:
        The total latency assuming sequential execution of all nodes
    """
    return fold(
        tree,
        lambda node, subs, next_result:
            node.latency + sum(subs) + (next_result if next_result is not None else 0)
    )

def total_calls(tree: TreeTraceNode) -> int:
    """
    Count the total number of generation calls in the tree trace.

    This function counts the total number of nodes in the tree, which corresponds
    to the total number of generation calls made during the recursive process.

    Args:
        tree: The root TreeTraceNode to count calls for

    Returns:
        The total number of generation calls (nodes) in the tree
    """
    return fold(
        tree,
        lambda _, subs, next_result:
            1 + sum(subs) + (next_result if next_result is not None else 0)
    )

def max_depth(tree: TreeTraceNode) -> int:
    """
    Calculate the maximum depth of the tree trace.

    This function computes the maximum depth of the tree, which corresponds
    to the deepest level of recursion reached during the generation process.

    Args:
        tree: The root TreeTraceNode to calculate depth for

    Returns:
        The maximum depth of the tree
    """
    return len(nodes_per_level(tree)) - 1

def max_subproblem(tree: TreeTraceNode) -> int:
    """
    Calculate the maximum number of subproblems at any level in the tree trace.

    This function computes the maximum number of subproblems (children) that any node in the tree has,
    which corresponds to the maximum branching factor of the recursive generation process.

    Args:
        tree: The root TreeTraceNode to calculate max subproblems for

    Returns:
        The maximum number of subproblems at any level in the tree
    """
    return fold(
        tree,
        lambda node, subs, next_result:
            max([len(node.subproblems)] + subs + ([next_result] if next_result is not None else []))
    )

def max_output_character(tree: TreeTraceNode) -> int:
    """
    Find the maximum number of characters in any output across the tree trace.

    This function traverses all nodes and returns the length of the longest
    output string found in any node.

    Args:
        tree: The root TreeTraceNode to analyze

    Returns:
        The maximum number of characters in any node's output
    """
    return fold(
        tree,
        lambda node, subs, next_result:
            max([len(node.output)] + subs + ([next_result] if next_result is not None else []))
    )


def nodes_per_level(tree: TreeTraceNode) -> List[int]:
    """
    Analyze the number of nodes at each level of the tree trace.

    This function counts how many nodes exist at each depth level in the tree,
    providing insight into the tree's structure and branching behavior.

    Args:
        tree: The root TreeTraceNode to analyze

    Returns:
        A list of integers where index i contains the count of nodes at depth i

    Example:
        >>> root = TreeTraceNode("Solve X+Y", "", 0)
        >>> # ... build tree with nodes at depth 0, 1, 2 ...
        >>> counts = nodes_per_level(root)
        >>> # Returns: [3, 5, 2] meaning 3 nodes at depth 0, 5 at depth 1, 2 at depth 2
    """
    def combine(node, subs, next_result):
        # Start with current node's depth
        result = {node.depth: 1}

        # Merge all subproblem counts
        for sub_dict in subs:
            for depth, count in sub_dict.items():
                result[depth] = result.get(depth, 0) + count

        # Merge next node's counts
        if next_result is not None:
            for depth, count in next_result.items():
                result[depth] = result.get(depth, 0) + count

        return result

    counts = fold(tree, combine)

    # Convert the dictionary to a list
    if not counts:
        return []

    max_depth_level = max(counts.keys())
    result = [counts.get(i, 0) for i in range(max_depth_level + 1)]

    return result